database:
  connection:
    host: "localhost"
    port: 27017
    username: "PetTracker"  # Leave empty if no authentication is required
    password: "PetTracker"  # Leave empty if no authentication is required
  settings:
    name: "IoT_Pet_Tracker_db"  # Your database name
    auth_source: "admin"
